### ISSUE TITLE
Augmenter % de la partie auteur

### ISSUE THREAD

**Issue by luciaLebrun** [guilhemmazoyer/Parseur_lbgl#17]
% actuel : 48,64 
_( La moyenne comprend la non ouverture de 3 fichiers )_

Formule regex actuelle : 
```regex
REGEX_ALL_EMAILS = r"{?\(?\b[\w][\w, .-]*[a-z\d]\)?}?\n?[@|Q][\w\-_.]+"
REGEX_TYPE_MULTI_EMAILS = r"({|\()?([\w.\- ]+,[\w.\- ]+)+(\)|})?\n?@[\w\-_.]+"
```
L'affiliation est comprise dans la partie auteur et pourra être modifiée.

**Comment by guilhemmazoyer** [comment]
@Kazh-boop cover that issue
