### ISSUE TITLE
S4 Nouvelles parties

### ISSUE THREAD

**Issue by guilhemmazoyer** [guilhemmazoyer/Parseur_lbgl#9]
Récupération de :
- [x] Abstract
- [x] Introduction
- [ ] Corps
- [x] Conclusion ⚠️ le titre est affiché
- [x] Discussion
- [x] Biblios

**Comment by luciaLebrun** [comment]
# Introduction

- [x] Das_Martins
- [x] Gonzales
- [x] Iria_Juan
- [x] Jing-cutepaste 
- [ ] Kessler94715
- [ ] KesslerMetics
- [ ] Mikheev
- [x] Mikolov
- [x] Nasr
- [ ] TorresMoreno
- [ ] Torres

**Comment by luciaLebrun** [comment]
# Conclusion
```
(Conclusion.*)\n(.|\n)*(?=References|Acknowledgements|Follow-Up Work)
```

**Comment by luciaLebrun** [comment]
# Discussion
```regex

```
- [] Das_Martins
- [] Gonzales
- [] Iria_Juan
- [] Jing-cutepaste 
- [] Kessler94715
- [] KesslerMetics
- [] Mikheev
- [] Mikolov
- [] Nasr
- [] TorresMoreno
- [] Torres

**Comment by luciaLebrun** [comment]
# Corps
```regex
(\n2|II).??(.|\n)*(?=Conclusion|Discussion)
```
- [ ] Das_Martins
- [ ] Gonzales
- [ ] Iria_Juan
- [ ] Jing-cutepaste
- [ ] Kessler94715
- [ ] KesslerMetics
- [ ] Mikheev
- [ ] Mikolov
- [ ] Nasr
- [ ] TorresMoreno
- [ ] Torres
